---
- name: Instalando o IIS no Windows Server
  hosts: windows
  tasks:
  - name: Instalando IIS      
    win_feature:        
      name: "Web-Server"        
      state: present

  - name: Iniciando IIS
    win_service:
      name: W3Svc
      state: started

  - name: Criando arquivo index.html           
    win_copy:
      content: Conex√£o do IIS Trabalho Devops
      dest: C:\Inetpub\wwwroot\index.html-